"""create requests table

Revision ID: 055835debc18
Revises: e8953246b4fe
Create Date: 2025-03-04 22:08:47.166598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055835debc18'
down_revision: Union[str, None] = 'e8953246b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_superitendence', sa.Integer(), nullable=False),
    sa.Column('departure_location', sa.String(length=50), nullable=False),
    sa.Column('destination_location', sa.String(length=50), nullable=False),
    sa.Column('date_request', sa.Date(), nullable=False),
    sa.Column('time_request', sa.Time(), nullable=False),
    sa.Column('number_peoples', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'ACEITO', 'RECUSADO', 'FINALIZADO', name='requestsstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_superitendence'], ['superitendences.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
